### ISSUE TITLE
Inicio de Sesión

### ISSUE THREAD

**Issue by JRF344** [Fiji-exe/CineManager#6]
**SOURCES**
Wireframe by Joshua: https://drive.google.com/file/d/1koe9uCjeSgKgRolCOUiVGOJa8lLCu3FY/view?usp=sharing
EDS : https://docs.google.com/document/d/1_4ntxsQx9aIwbAgh21Yl212WtKbGM6JGgCaHyqbNDjk/edit#
Code Templates : https://replit.com/@amurillog/tablasClaseProceso

- [ ] Html
   - [ ] header
      - [ ] href a fonts 
      - [ ] ver ejemplos del codigo de Factor Tecnico para checar que tiene el headers 
   - [ ] body
      - [ ] nav (ver Code Template de Abraham)
         - [ ] logo
         - [ ] boton acerca de
         - [ ] boton iniciar sesion 
      - [ ] content
         - [ ] frase bienvenida
         - [ ] recuadro de formulario
            - [ ] titulo de inicio de sesion
            - [ ] input email
            - [ ] input password
            - [ ] boton de iniciar sesion
            - [ ] a href a seccion de recuperar contraseña 
    - [ ] footer
- [ ] JS (Opcional, o de ultimo. Ya que JS no es tan primordial para esta primera entrega)
    - [ ] Asociar la accion de redireccion a cada boton 
- [ ] CSS (al crearlo, tenern en cuenta que su CSS se usara luego para la creacion de un CSS general)
   - [ ] posicionamiento
   - [ ] color 
   - [ ] estilo de botones
   - [ ] backgrounds

**Comment by adriand00** [comment]
Se chequeo el branch inicio-de-sesion y no hay updates

![image](https://user-images.githubusercontent.com/58629163/139553983-8d71517a-745e-4944-a4d9-affc5394d520.png)

**Comment by adriand00** [comment]
Se chequeo el branch inicio-de-sesion y no hay updates
![image](https://user-images.githubusercontent.com/58629163/139604303-9b63d16d-1c46-4ee4-a1df-e999d0235343.png)

**Comment by adriand00** [comment]
Se chequeo el branch inicio-de-sesion y no hay updates
![image](https://user-images.githubusercontent.com/58629163/140054781-6684528d-f09e-4201-8fac-2626a555ea99.png)

**Comment by adriand00** [comment]
Se chequeo el branch inicio-de-sesion y no hay updates
![image](https://user-images.githubusercontent.com/58629163/140616093-c3aae7e7-0e6b-465a-94c4-878cbb8c05d8.png)

**Comment by JRF344** [comment]
Debido a la cantidad de similaridades entre paginas, inicio de sesion y registro usuario cliente se combinaron
