### ISSUE TITLE
Registro usuario cliente  (registro público solamente)

### ISSUE THREAD

**Issue by JRF344** [Fiji-exe/CineManager#8]
**SOURCES**
Wireframe by joshua: https://drive.google.com/file/d/1jldSFKbISHLhs_kGhEvtMMSIfVcAv8hz/view?usp=sharing
EDS : https://docs.google.com/document/d/1_4ntxsQx9aIwbAgh21Yl212WtKbGM6JGgCaHyqbNDjk/edit#
Code Templates : https://replit.com/@amurillog/tablasClaseProceso

- [x] Html
   - [x] header
      - [x] href a fonts 
      - [x] ver ejemplos del codigo de Factor Tecnico para checar que tiene el headers 
   - [x] body
      - [ ] nav (ver Code Template de Abraham)
         - [ ] logo
         - [ ] boton menu principal
         - [ ] boton salir
      - [x] content
          - [x] contenedor
             - [x] flecha regresar
             - [x] titulo
             - [x] formulario
                - [x] inputs para cada requisito
                - [x] titulos de cada input
                - [x] textarea para instrucciones con los requisitos de la contraseña
                - [x] img para avatar
                - [x] boton para cargar imagen avatar
                - [x] boton registrar
                - [x] a href para iniciar sesion
    - [ ] footer
- [ ] JS (Opcional, o de ultimo. Ya que JS no es tan primordial para esta primera entrega)
    - [x] Asociar la accion de redireccion a cada boton 
- [x] CSS (al crearlo, tenern en cuenta que su CSS se usara luego para la creacion de un CSS general)
   - [x] posicionamiento
   - [x] color 
   - [x] estilo de botones
   - [x] estilo de inputs
   - [x] backgrounds

**Comment by adriand00** [comment]
Pending
- instrucciones con requisitos de contrasenna
- cedula dropdown menu 
- boton crear rediriga (si todo es valido) a validar OTP
- espacio para segundo nombre y segundo apellido
- espacio para fecha de nacimiento
- formulario no resalta en rojo cuando nombre/apellido/cedula esta vacio

Notes: validar OTP se revisa desde el Issue en GitHub Recuperar-contraseña

**Comment by adriand00** [comment]
Pending

instrucciones con requisitos de contrasenna
instrucciones de como introducir el numero de cedula
populate cedula dropdown menu
boton crear rediriga (si todo es valido) a validar OTP
espacio para segundo nombre y segundo apellido
espacio para fecha de nacimiento
Placeholders no tienen la fuente tipofrafica del proyecto
~~formulario no resalta en rojo cuando nombre/apellido/cedula esta vacio~~

Notes: validar OTP se revisa desde el Issue en GitHub Recuperar-contraseña

**Comment by JRF344** [comment]
Resto de cambios en c9e426953f06ae4f0c4f2df2f89492bc00ca1cd8

- Ademas de Cedula de identidad y DIMEX, que tipos de cedula vamos a soportar?
- Que formatos requieren dichas cedulas
