### ISSUE TITLE
Pagina para recuperación de contraseña

### ISSUE THREAD

**Issue by JRF344** [Fiji-exe/CineManager#9]
**SOURCES**
Wireframe by Joshua: https://drive.google.com/file/d/1VDfLUlXrnNZrZnZ8GoAUY1vP6-8J57yb/view?usp=sharing
EDS : https://docs.google.com/document/d/1_4ntxsQx9aIwbAgh21Yl212WtKbGM6JGgCaHyqbNDjk/edit#
Code Templates : https://replit.com/@amurillog/tablasClaseProceso

- [x] Html
   - [x] header
      - [x] href a fonts 
      - [x] ver ejemplos del codigo de Factor Tecnico para checar que tiene el headers 
   - [x] body
      - [x] nav (ver Code Template de Abraham)
         - [x] logo
         - [x] boton acerca de
         - [x] boton iniciar sesion 
      - [x] content
         - [x] frase bienvenida
         - [x] recuadro de formulario
            - [x] titulo
            - [x] input email
            - [x] boton regresar
    - [x] footer
- [ ] JS (Opcional, o de ultimo. Ya que JS no es tan primordial para esta primera entrega)
    - [ ] Asociar la accion de redireccion a cada boton 
- [x] CSS (al crearlo, tenern en cuenta que su CSS se usara luego para la creacion de un CSS general)
   - [x] posicionamiento
   - [x] color 
   - [x] estilo de botones
   - [x] backgrounds

**Comment by adriand00** [comment]
Se chequeo el branch recuperar-contraseña y no hay updates

![image](https://user-images.githubusercontent.com/58629163/139554034-f1ae9670-87a2-42b8-b883-871818eae17b.png)

**Comment by adriand00** [comment]
Pending
El pop up "se ha enviado un correo de recuperacion" esta asignado al boton "Validar" 
      (este pop up deberia estar asignado al boton "Recuperar")
Flecha de atras en Recuperar Contraseña rediriga a landing-page HTML 
Con el email "echo@gmail.com"


![image](https://user-images.githubusercontent.com/58629163/139602696-b5856e10-ea4e-47a4-9caf-b715dae38f38.png)
![image](https://user-images.githubusercontent.com/58629163/139602732-7977815b-09fa-448f-8fe4-d3391a3ae05d.png)

**Comment by adriand00** [comment]
Pending

El pop up "se ha enviado un OTP de recuperacion" esta asignado al boton "Validar"
(este popup deberia estar asignado al boton "Recuperar")
luego de mostrar el mensaje "se ha enviado un correo de recuperacion" redirigir a Validar Codigo HTML
Flecha de atras en Recuperar Contraseña rediriga a landing-page HTML (en cuanto este disponible)
Agregar un form para que el cliente pueda ingresar nueva contraseña (No se agrego durante los Wireframes)

**Comment by adriand00** [comment]
Pending 
El pop up "se ha enviado un OTP de recuperacion" esta asignado al boton "Validar"
(este popup deberia estar asignado al boton "Recuperar")
luego de mostrar el mensaje "se ha enviado un correo de recuperacion" redirigir a Validar Codigo HTML
Flecha de atras en Recuperar Contraseña rediriga a landing-page HTML (en cuanto este disponible)
Agregar un form para que el cliente pueda ingresar nueva contraseña (No se agrego durante los Wireframes)
